"""The master record: one row per demand, the suggestions and the decision side by side."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from ..models import Demand, DemandStatus


class Registry(Protocol):
    kind: str

    def create(self, demand: Demand) -> None: ...
    def update(self, demand: Demand) -> None: ...
    def get(self, demand_id: str) -> Demand | None: ...
    def by_conversation(self, conversation_id: str) -> Demand | None: ...
    def by_task(self, task_id: str) -> Demand | None: ...
    def list(
        self, *, area: str | None = None, status: DemandStatus | None = None
    ) -> list[Demand]: ...
    def message_processed(self, message_id: str) -> bool: ...
    def record_message(self, message_id: str, *, result: str, received_at: datetime) -> None: ...
    def processed_messages(self) -> list[dict]: ...
